### ISSUE TITLE
克隆代码后，本地编译失败，求帮助

### ISSUE THREAD

**Issue by stuartZhang** [shadowsocks/crypto#2]
大神，

是不是，我本地使用的 rustc 版本太老了，还是需要安装一些其它的东西，才能解决 the trait `std::array::LengthAtMost32` is not implemented for `[u8; 64]` 的问题呀？

![image](https://user-images.githubusercontent.com/13935927/97284602-33dc0280-187c-11eb-9642-a4763f0a33b0.png)

**Comment by LuoZijun** [comment]
更新至最新的版本的 Rust Nightly 编译器应该就没有问题。

```bash
$ rustup update
$ rustup default nightly
```

如果不想更新，可以在调用 `md2` 函数的时候，手动取 `slice`：
```rust
let data = [1u8; 1000];
md2(&data[..]);
```
