### ISSUE TITLE
Incompatibility issue after Rustc upgrade

### ISSUE THREAD

**Issue by jing-951** [shadowsocks/crypto#33]
Boss, after the Rustc upgrade (Rustc 1.81.0 slightly (d8a38b000 2024-06-19)), there are two features that cannot be used: stdsimd and llvm-asm

**Comment by zonyitoo** [comment]
Are they stablized in 1.81.0? Or just removed?

**Comment by jing-951** [comment]
> Are they stablized in 1.81.0? Or just removed?

Yes, he was removed

**Comment by zonyitoo** [comment]
Couldn't reproduce with `rustc 1.81.0-nightly (bcf94dec5 2024-06-23)`.
