### ISSUE TITLE
疑似缺陷bug: 使用此 crypto 包 sm4 -cbc 加密的密文不能被 JAVA 版 sm4 包解密。求帮助！

### ISSUE THREAD

**Issue by stuartZhang** [shadowsocks/crypto#4]
大神呀！

我使用由此 crypto 包交叉编译而来的  wasm - npm 依赖，从前端 sm4 - cbc 加密明文。然后，传输【密文】给后端 java web server 解密。但是，后端 java web server 不能成功解密。**注意：crypto 包是能够成功解密自己加密的密文的。关于此，我写过单元测试，验证过了。**

通过与后端 java web server 大牛的反复沟通（我是不会后端的小前端一枚），他们给我一个[【京东数科】的在线【SM4 - 128位 - cbc】加密与解密工具](https://aks.jd.com/tools/sec/)。而且，java 大牛告诉我：“后端使用的 java 版本**128 位 sm4 cbc**加密与解密结果与[【京东数科】在线工具](https://aks.jd.com/tools/sec/)一致”。

然后，我使用[【京东数科】在线工具](https://aks.jd.com/tools/sec/)，加密了一段内容：

- Key(16): 1234567890123456
- nonce(16): abcdefghijkmlnop
- padding模式: nopadding
- 明文(16): zyxwvusrqponlmkj

结果密文：

- Hex: 8ea150185ca6fc6937a2014be655f01a

![image](https://user-images.githubusercontent.com/13935927/97796066-8fc1d500-1c48-11eb-82b2-a563334487ca.png)

![image](https://user-images.githubusercontent.com/13935927/97796071-96e8e300-1c48-11eb-824f-1cd20974112f.png)

接着，我在咱们 crypto 包的`src\blockmode\cbc.rs`文件里，添加了一个新单元测试：

```rust
#[test]
fn test_sm4_enc() { // https://aks.jd.com/tools/sec/
    let key = "1234567890123456".as_bytes();
    let nonce = "abcdefghijkmlnop".as_bytes();
    let plain_text = "zyxwvusrqponlmkj".as_bytes(); // 十六位，不需要填充，所以是 nopadding 模式
    let mut cipher = Sm4Cbc::new(&key, &nonce);
    let mut cipher_text = Vec::new();
    cipher_text.extend_from_slice(plain_text);
    cipher.encrypt(&mut cipher_text);
    let cipher_text = hex::encode(cipher_text);
    assert_eq!(cipher_text, "8ea150185ca6fc6937a2014be655f01a");
}
```

在运行了上面的单元测试之后，我发现它们的加密结果真的不一样。咱们 crypto 包的加密结果是：b5330fcbc79100ddcc7caa8534ea66f5

![image](https://user-images.githubusercontent.com/13935927/97796020-43769500-1c48-11eb-8308-0817f4ed2a1c.png)

最后，请 @LuoZijun 等大神们看一眼，是我在单元测试里写的调用方式不对（会不会是我直接使用`.as_bytes()`是不对的？），还是咱们伟大的 crypto 包真的有缺陷。

**Comment by LuoZijun** [comment]
SM4
```bash
curl "https://aks.jd.com/tools/sec/sm4Enc" \
    -H "Referer: https://aks.jd.com/tools/sec/" \
    -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
    --data-raw "sm4DecSrcData=zyxwvusrqponlmkj&activeTab=SM4&keyLength=128&sm4Mode=CBC&sm4IsPadding=nopadding&sm4Iv=abcdefghijkmlnop&sm4Key=1234567890123456" \
    | python3 -m base64 -d | hexdump
```

AES:
```bash
curl "https://aks.jd.com/tools/sec/aesEnc" \
    -H "Referer: https://aks.jd.com/tools/sec/" \
    -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" \
    --data-raw "aesDecSrcData=zyxwvusrqponlmkj&activeTab=SM4&keyLength=128&aesMode=CBC&aesIsPadding=nopadding&aesIv=abcdefghijkmlnop&aesKey=1234567890123456" \
    | python3 -m base64 -d | hexdump```

 并没有问题。
